version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: clientsdb
    ports:
      - "5432:5432"
    networks:
      - clientnet

  client-manager:
    build: .
    depends_on:
      - postgres
    networks:
      - clientnet
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: testuser
      PGPASSWORD: testpass
      PGDATABASE: clientsdb

networks:
  clientnet: