services:
  db:
    image: postgres:16
    container_name: wtdbo_postgres
    environment:
      POSTGRES_USER: wtuser
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: wtdbo_db
    ports:
      - "5432:5432"
    volumes:
          - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
